function [fitresult, gof] = piecewiseFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'piecewise linear fitting' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2015 19:41:00


%% Fit: 'piecewise linear fitting'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'piecewise linear fitting' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'piecewise linear fitting', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


